name: JS Tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Bun Dependencies
        run: bun install

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          extensions: libxml
          tools: composer:v2

      - name: Install PHP dependencies
        run: composer install --no-interaction

      - name: Build
        run: bun run build:package

      - name: Prettier
        run: bun run fmt

      - name: ESLint
        run: bun run lint

      - name: Typescript
        run: bun run ts:check

      - name: Unit Tests And Coverage
        run: bun run test:coverage
